#! /bin/sh
export JAVA_HOME='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre/'
export API_M_HOME='/opt/apm/wso2'
startcmd='${API_M_HOME}/bin/wso2server.sh start > /dev/null &'
restartcmd='${API_M_HOME}/bin/wso2server.sh restart > /dev/null &'
stopcmd='${API_M_HOME}/bin/wso2server.sh stop > /dev/null &'

case "$1" in
start)
   echo "Starting the WSO2 Server ..."
   su -c "${startcmd}" wso2
;;
restart)
   echo "Re-starting the WSO2 Server ..."
   su -c "${restartcmd}" wso2
;;
stop)
   echo "Stopping the WSO2 Server ..."
   su -c "${stopcmd}" wso2
;;
*)
   echo "Usage: $0 {start|stop|restart}"
exit 1
esac
